### ISSUE TITLE
Allow config in YAML/JSON requests

### ISSUE THREAD

**Issue by thoom** [thoom/restup#37]
You can currently build a YAML/JSON file as part of a request. It would be great if you could add something like `_conf` object that could store the request's configuration.

You could then run a command like `restup --conf get-request.yml` and it would populate headers, the url, method, etc.

The YAML could be something like:

```
_conf:
  url: https://ex.io/api/endpoint
  method: get
  headers:
     cookie: someCookie=someValue
  flags: [verbose, j]
```
